trigger:
- main

variables:
  SOME_VAR: "My Var"
  
stages:
  - stage: Deploy
    jobs:
      - job: Deploy
        pool: 
         name: courseplatform_dev_runner
        steps:
          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: 'Run a multi-line script'
