version: '3.1'

services:
  db:
    image: postgres:10.5
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATA_DIR=./postgres-data:/var/lib/postgresql/data

