version: '3.2'

services:
  course-svc-postgres:
    container_name: course-svc-postgres
    image: postgres:14.2-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=course-svc

#   rabbitmq:
#     image: rabbitmq:3-management-alpine
#     container_name: 'rabbitmq'
#     ports:
#       - 5672:5672
#       - 15672:15672
#     volumes:
#       - $PWD/rabbitmq/data/:/var/lib/rabbitmq/
#       - $PWD/rabbitmq/log/:/var/log/rabbitmq
#     networks: 
#       - rabbitmq_go_net
  
# networks:
#   rabbitmq_go_net:
#     driver: bridge
  # course_svc:
  #   build: ./course-service
  #   container_name: course-svc
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - .:/home/node/app
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal/course-svc
  #     - JWT_SECRET=secret
  #   depends_on:
  #     - course-svc-postgres
  #   links:
  #     - course-svc-postgres

  # email_microservice:
  #   build: ./email-microservice
  #   container_name: email-microservice
  #   restart: always
  #   tty: true
  #   volumes:
  #     - .:/home/node/app 