version: '3.1'

services:
  db:
    image: postgres:14.2
    restart: always
    container_name: cp-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courseplatform

  # course_platform:
  #   build: ./course-platform
  #   container_name: course-platform-api
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - .:/home/node/app
  #   depends_on:
  #     - db



  # email_microservice:
  #   build: ./email-microservice
  #   container_name: email-microservice
  #   restart: always
  #   tty: true
  #   volumes:
  #     - .:/home/node/app 